from __future__ import annotations

import hashlib
import html
import re
import urllib.parse
from collections import Counter
from dataclasses import dataclass
from typing import Any


BLOCK_CODES = {403, 406, 412, 418, 429, 503, 999}
BLOCK_KEYWORDS = (
    "access denied",
    "attack detected",
    "automated requests",
    "bot detected",
    "incident id",
    "intrusion detected",
    "not acceptable",
    "request blocked",
    "request not allowed",
    "requested url was rejected",
    "security policy",
    "support id",
    "threat detected",
    "web application firewall",
)
WAF_HEADERS = {
    "Cloudflare": ("cf-mitigated", "cf-ray"),
    "Akamai": ("x-akamai-request-id", "akamai-origin-hop"),
    "AWS WAF / CloudFront": ("x-amz-cf-id", "x-amzn-requestid"),
    "Imperva / Incapsula": ("x-iinfo",),
    "Sucuri": ("x-sucuri-id",),
    "F5 BIG-IP ASM": ("x-wa-info", "x-f5-request-id"),
    "ModSecurity / OWASP CRS": ("x-modsecurity-rule-id",),
    "Azure Front Door WAF": ("x-azure-ref", "x-azure-fdid"),
}
WAF_BODY = {
    "Cloudflare": ("cloudflare ray id", "attention required", "cf-browser-verification"),
    "Akamai": ("access denied", "reference #", "akamai"),
    "Imperva / Incapsula": ("incapsula incident", "_incapsula_resource"),
    "Sucuri": ("sucuri website firewall", "access denied - sucuri"),
    "F5 BIG-IP ASM": ("the requested url was rejected", "your support id is"),
    "ModSecurity / OWASP CRS": ("406 not acceptable", "generated by mod_security"),
    "Google Cloud Armor": ("google cloud armor", "your client does not have permission"),
}


@dataclass(frozen=True)
class AdaptiveDecision:
    stop_module: bool = False
    stop_input: bool = False
    blocked: bool = False
    reason: str = ""
    signature: str = ""
    repetitions: int = 0
    vendor: str = ""


class AdaptiveResponseGuard:
    """Stops low-value active probes after repeated equivalent responses."""

    def __init__(self, *, block_threshold: int = 6, plateau_threshold: int = 8) -> None:
        self.block_threshold = max(3, int(block_threshold))
        self.plateau_threshold = max(4, int(plateau_threshold))
        self.stop_module = False
        self.stop_reason = ""
        self.waf_vendor = ""
        self._block_signatures: Counter[str] = Counter()
        self._input_signatures: Counter[tuple[str, str]] = Counter()
        self._stopped_inputs: dict[str, str] = {}

    def input_stopped(self, input_key: str) -> bool:
        return input_key in self._stopped_inputs

    def observe(
        self,
        result: Any,
        *,
        input_key: str,
        probe_value: str = "",
        baseline: Any = None,
        positive_signal: bool = False,
    ) -> AdaptiveDecision:
        if self.stop_module:
            return AdaptiveDecision(stop_module=True, blocked=True, reason=self.stop_reason, vendor=self.waf_vendor)
        if not result:
            return AdaptiveDecision()

        signature = self.response_signature(result, probe_value)
        vendor = self.detect_waf_vendor(result)
        blocked = self.looks_blocked(result, vendor)
        status = int(getattr(result, "status", 0) or 0)
        size = int(getattr(result, "body_len", 0) or 0)

        if blocked:
            self._block_signatures[signature] += 1
            repetitions = self._block_signatures[signature]
            if repetitions >= self.block_threshold:
                vendor_label = vendor or "proteccion perimetral/aplicacion"
                self.waf_vendor = vendor_label
                self.stop_reason = (
                    f"cortacircuito WAF: {repetitions} respuestas equivalentes "
                    f"status={status} tamano={size}b proveedor={vendor_label}"
                )
                self.stop_module = True
                return AdaptiveDecision(
                    stop_module=True,
                    blocked=True,
                    reason=self.stop_reason,
                    signature=signature,
                    repetitions=repetitions,
                    vendor=vendor_label,
                )
            return AdaptiveDecision(
                blocked=True,
                signature=signature,
                repetitions=repetitions,
                vendor=vendor,
            )

        if positive_signal:
            return AdaptiveDecision(signature=signature, vendor=vendor)

        baseline_signature = self.response_signature(baseline, "scan_titan_control") if baseline else ""
        plateau_key = (input_key, signature)
        self._input_signatures[plateau_key] += 1
        repetitions = self._input_signatures[plateau_key]
        unchanged = bool(baseline_signature and signature == baseline_signature)
        if repetitions >= self.plateau_threshold:
            reason = (
                f"entrada sin variacion: {repetitions} respuestas equivalentes "
                f"status={status} tamano={size}b"
            )
            if unchanged:
                reason += " iguales al control"
            self._stopped_inputs[input_key] = reason
            return AdaptiveDecision(
                stop_input=True,
                reason=reason,
                signature=signature,
                repetitions=repetitions,
                vendor=vendor,
            )
        return AdaptiveDecision(signature=signature, repetitions=repetitions, vendor=vendor)

    def summary(self) -> dict[str, Any]:
        return {
            "module_stopped": self.stop_module,
            "stop_reason": self.stop_reason,
            "waf_vendor": self.waf_vendor,
            "stopped_inputs": len(self._stopped_inputs),
            "input_stop_reasons": dict(self._stopped_inputs),
            "block_signatures": sum(self._block_signatures.values()),
        }

    @classmethod
    def looks_blocked(cls, result: Any, vendor: str = "") -> bool:
        status = int(getattr(result, "status", 0) or 0)
        body = str(getattr(result, "text", "") or "").lower()[:30000]
        keyword_hits = sum(1 for keyword in BLOCK_KEYWORDS if keyword in body)
        vendor_body = any(
            marker in body
            for markers in WAF_BODY.values()
            for marker in markers
        )
        return status in BLOCK_CODES or vendor_body or keyword_hits >= 2 or (bool(vendor) and keyword_hits >= 1)

    @classmethod
    def detect_waf_vendor(cls, result: Any) -> str:
        if not result:
            return ""
        headers = {str(key).lower(): str(value).lower() for key, value in getattr(result, "headers", {}).items()}
        body = str(getattr(result, "text", "") or "").lower()[:30000]
        matches: list[str] = []
        for name, markers in WAF_HEADERS.items():
            if any(marker in headers for marker in markers):
                matches.append(name)
        for name, markers in WAF_BODY.items():
            if any(marker in body for marker in markers):
                matches.append(name)
        server = headers.get("server", "")
        if "cloudflare" in server:
            matches.append("Cloudflare")
        elif "akamai" in server:
            matches.append("Akamai")
        return " | ".join(dict.fromkeys(matches))

    @classmethod
    def response_signature(cls, result: Any, probe_value: str = "") -> str:
        if not result:
            return ""
        status = int(getattr(result, "status", 0) or 0)
        size = int(getattr(result, "body_len", 0) or 0)
        content_type = str(getattr(result, "content_type", "") or "").split(";", 1)[0].lower()
        body = str(getattr(result, "text", "") or "")[:60000].lower()
        for variant in cls._probe_variants(probe_value):
            if variant:
                body = body.replace(variant.lower(), "<probe>")
        body = re.sub(r"\b[0-9a-f]{8}-[0-9a-f-]{27,}\b", "<uuid>", body)
        body = re.sub(r"\b(?:request|incident|support|reference|ray)[\s:#_-]*[a-z0-9_-]{6,}\b", "<event-id>", body)
        body = re.sub(r"\b\d{6,}\b", "<number>", body)
        body = re.sub(r"\s+", " ", body).strip()
        digest = hashlib.sha256(body.encode("utf-8", errors="ignore")).hexdigest()[:16]
        return f"{status}:{size}:{content_type}:{digest}"

    @staticmethod
    def _probe_variants(value: str) -> list[str]:
        text = str(value or "")
        if not text:
            return []
        return list(
            dict.fromkeys(
                [
                    text,
                    urllib.parse.quote(text, safe=""),
                    urllib.parse.quote_plus(text, safe=""),
                    urllib.parse.unquote(text),
                    html.escape(text, quote=True),
                    html.escape(text, quote=False),
                ]
            )
        )
