from __future__ import annotations

import random
import re
import urllib.parse
from dataclasses import dataclass
from typing import Any

from .common import Finding, ScanContext, VulnerabilityModule, clean_text


BLOCK_CODES = {400, 401, 403, 405, 406, 412, 418, 429, 501, 502, 503, 999}
BLOCK_KEYWORDS = (
    "access denied",
    "attack detected",
    "blocked",
    "bot detected",
    "firewall",
    "incident id",
    "intrusion",
    "not acceptable",
    "request not allowed",
    "security policy",
    "support id",
    "threat detected",
    "waf",
)

WAF_HEADER_SIGNATURES = {
    "Cloudflare": ("cf-ray", "cf-cache-status", "cf-request-id", "cf-mitigated"),
    "Akamai": ("x-akamai-request-id", "x-check-cacheable", "akamai-origin-hop"),
    "AWS WAF / CloudFront": ("x-amz-cf-id", "x-amz-request-id", "x-amzn-requestid"),
    "Imperva / Incapsula": ("x-iinfo", "x-cdn"),
    "Sucuri": ("x-sucuri-id", "x-sucuri-cache"),
    "Fastly / Signal Sciences": ("x-fastly-request-id", "x-served-by"),
    "Reblaze": ("x-reblaze-uid", "x-reblaze-request-id"),
    "F5 BIG-IP ASM": ("x-cnection", "x-wa-info", "x-f5-request-id"),
    "Fortinet FortiWeb": ("x-fw-debug",),
    "Barracuda WAF": ("x-barracuda-url", "x-barracuda-connect"),
    "Citrix NetScaler": ("citrix-transactionid",),
    "Radware AppWall": ("x-radware-appwall-attack",),
    "ModSecurity / OWASP CRS": ("x-modsecurity-rule-id",),
    "NAXSI / Nginx": ("x-data-origin",),
    "Wallarm NG WAF": ("x-wallarm-node", "x-wallarm-request-id"),
    "Azure Front Door WAF": ("x-azure-ref", "x-fd-healthprobe", "x-azure-fdid"),
    "Google Cloud Armor": ("x-goog-iap-generated-response",),
    "StackPath WAF": ("x-sp-url", "x-sp-waf"),
    "IBM DataPower": ("x-datapower-transactionid",),
    "Varnish / CacheWall": ("x-varnish",),
    "Comodo cWatch": ("x-comodo-waf", "x-cwaf"),
    "OpenResty WAF": ("x-openresty-waf",),
    "LiteSpeed WAF": ("x-litespeed-cache",),
}

WAF_COOKIE_SIGNATURES = {
    "Cloudflare": ("__cflb", "__cfuid", "cf_clearance", "__cf_bm"),
    "AWS WAF / CloudFront": ("awsalb", "awsalbcors", "awswaf"),
    "Akamai Kona / SiteDefender": ("ak_bmsc", "bm_sz", "_abck", "bm_sv"),
    "Imperva / Incapsula": ("incap_ses", "visid_incap", "nlbi_"),
    "F5 BIG-IP ASM": ("bigipserver", "f5_cspm", "ts01"),
    "Fortinet FortiWeb": ("fortiwafsid",),
    "Barracuda WAF": ("barra_counter_session", "bni__barracuda_lb_cookie"),
    "Citrix NetScaler": ("nsc_", "citrix_ns_id"),
    "Reblaze": ("rbzid", "rbzsessionid"),
    "Wordfence": ("wfvt_", "wordfence_verifiedhuman"),
}

WAF_BODY_SIGNATURES = {
    "Cloudflare": (
        "cloudflare ray id",
        "attention required",
        "checking if the site connection is secure",
        "cf-browser-verification",
    ),
    "Akamai Kona / SiteDefender": ("access denied", "reference #", "akamai"),
    "Imperva / Incapsula": ("incapsula incident", "_incapsula_resource", "request unsuccessful"),
    "Sucuri": ("sucuri website firewall", "access denied - sucuri"),
    "F5 BIG-IP ASM": ("the requested url was rejected", "your support id is"),
    "ModSecurity / OWASP CRS": ("406 not acceptable", "this error was generated by mod_security"),
    "Radware AppWall": ("unauthorized activity has been detected", "radware"),
    "Google Cloud Armor": ("your client does not have permission", "google cloud armor"),
}


@dataclass(frozen=True)
class WafProbe:
    categoria: str
    parametro: str
    payload: str
    tecnica: str
    headers: dict[str, str]


class WafResilienceModule(VulnerabilityModule):
    name = "waf_resilience"

    BASE_PROBES = {
        "SQLi": ("id", "1' OR '1'='1"),
        "XSS": ("q", "<script>alert(1)</script>"),
        "LFI": ("file", "../../../../etc/passwd"),
        "RCE": ("cmd", ";id;"),
        "SSTI": ("tpl", "{{7*7}}"),
        "SSRF": ("url", "http://127.0.0.1:9/scan-titan"),
    }

    HEADER_VARIANTS = [
        ("navegador", {}),
        ("ip-interna-x-forwarded-for", {"X-Forwarded-For": "127.0.0.1"}),
        ("ip-interna-x-real-ip", {"X-Real-IP": "127.0.0.1"}),
        ("ip-cliente-original", {"X-Client-IP": "127.0.0.1", "X-Originating-IP": "127.0.0.1"}),
        ("forwarded-rfc", {"Forwarded": "for=127.0.0.1;proto=https;host=localhost"}),
        ("ruta-original", {"X-Original-URL": "/admin"}),
        ("ruta-rewrite", {"X-Rewrite-URL": "/admin"}),
        ("override-metodo", {"X-HTTP-Method-Override": "GET"}),
        ("host-local", {"Host": "localhost"}),
    ]

    async def run(self, ctx: ScanContext) -> list[Finding]:
        baseline = await ctx.http.request(
            "GET",
            ctx.target.url,
            allow_redirects=False,
            timeout=min(ctx.limits.timeout, 8),
        )
        header_waf = self._header_waf_signal(baseline)
        if header_waf:
            ctx.recon["waf_cdn"] = sorted(set(ctx.recon.get("waf_cdn", []) + [header_waf]))

        probes = self._build_probes(ctx)
        budget = min(ctx.limits.max_tests_per_module, len(probes))
        records: list[dict[str, Any]] = []
        blocked = 0
        rate_limited = 0
        passed = 0

        for index, probe in enumerate(probes[:budget], start=1):
            ctx.heartbeat(self.name, f"{probe.categoria}:{probe.tecnica}", index, blocked)
            result = await ctx.http.request(
                "GET",
                ctx.target.url,
                params={probe.parametro: probe.payload},
                headers=self._headers(probe.headers),
                allow_redirects=False,
                timeout=min(ctx.limits.timeout, 8),
            )
            verdict = self._verdict(result, probe.payload)
            if verdict == "bloqueado":
                blocked += 1
            elif verdict == "rate-limit":
                rate_limited += 1
            elif verdict == "permitido":
                passed += 1
            records.append(
                {
                    "categoria": probe.categoria,
                    "parametro": probe.parametro,
                    "tecnica": probe.tecnica,
                    "status": getattr(result, "status", 0) if result else 0,
                    "tamano": getattr(result, "body_len", 0) if result else 0,
                    "tiempo": f"{getattr(result, 'elapsed', 0.0):.2f}s" if result else "0.00s",
                    "veredicto": verdict,
                    "payload": clean_text(probe.payload, 180),
                }
            )

        summary = (
            f"WAF={header_waf or 'No identificado por cabeceras'} | "
            f"probados={len(records)} | bloqueados={blocked} | "
            f"rate-limit={rate_limited} | permitidos={passed}"
        )
        ctx.recon["waf_resilience_summary"] = summary
        ctx.recon["waf_probe_results"] = records[:500]

        findings: list[Finding] = []
        if header_waf or blocked or rate_limited:
            findings.append(
                Finding(
                    target=ctx.target.display,
                    category="Recon/WAF",
                    severity="Info",
                    title="Perfil de WAF y filtros de aplicacion observado",
                    url=ctx.target.url,
                    evidence=summary,
                    source=self.name,
                    confidence="medium" if header_waf else "low",
                )
            )
        return findings

    def _build_probes(self, ctx: ScanContext) -> list[WafProbe]:
        probes: list[WafProbe] = []
        source_payloads = {
            "SQLi": ctx.wordlists.get("sqli", [])[:12],
            "XSS": (ctx.wordlists.get("xss_payloads", []) or ctx.wordlists.get("xss", []))[:12],
            "LFI": ctx.wordlists.get("lfi", [])[:12],
            "RCE": ctx.wordlists.get("command_injection", [])[:12],
            "SSTI": ctx.wordlists.get("ssti", [])[:12],
            "SSRF": ctx.wordlists.get("ssrf", [])[:12],
        }
        for categoria, (parametro, default_payload) in self.BASE_PROBES.items():
            seeds = [default_payload, *source_payloads.get(categoria, [])]
            for payload in dict.fromkeys(str(item).strip() for item in seeds if str(item).strip()):
                for tecnica, mutated in self._mutations(payload):
                    for header_label, headers in self.HEADER_VARIANTS:
                        probes.append(
                            WafProbe(
                                categoria=categoria,
                                parametro=parametro,
                                payload=mutated,
                                tecnica=f"{tecnica}/{header_label}",
                                headers=headers,
                            )
                        )
        random.shuffle(probes)
        return probes

    def _mutations(self, payload: str) -> list[tuple[str, str]]:
        encoded = urllib.parse.quote(payload, safe="")
        double_encoded = urllib.parse.quote(encoded, safe="")
        comment_split = payload.replace(" ", "/**/")
        tab_split = payload.replace(" ", "%09")
        newline_split = payload.replace(" ", "%0a")
        mixed_case = self._mixed_case(payload)
        unicode_safe = self._unicode_compat(payload)
        candidates = [
            ("directo", payload),
            ("url-encoding", encoded),
            ("doble-url-encoding", double_encoded),
            ("comentarios", comment_split),
            ("tabuladores", tab_split),
            ("saltos-linea", newline_split),
            ("mayusculas-alternas", mixed_case),
            ("unicode-compatible", unicode_safe),
        ]
        unique: dict[str, tuple[str, str]] = {}
        for label, value in candidates:
            if value and len(value) <= 500:
                unique.setdefault(value, (label, value))
        return list(unique.values())

    def _headers(self, extra: dict[str, str]) -> dict[str, str]:
        headers = {
            "User-Agent": random.choice(
                [
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124 Safari/537.36",
                    "Mozilla/5.0 (X11; Linux x86_64) Chrome/124 Safari/537.36",
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 13_6) Safari/605.1.15",
                ]
            ),
            "Accept": "text/html,application/xhtml+xml,application/json,*/*;q=0.8",
            "Accept-Language": "es-GT,es;q=0.9,en;q=0.5",
        }
        headers.update(extra)
        return headers

    def _verdict(self, result: Any, payload: str) -> str:
        if not result:
            return "sin-respuesta"
        if result.status == 429:
            return "rate-limit"
        body = str(result.text or "").lower()
        keyword_hits = sum(1 for keyword in BLOCK_KEYWORDS if keyword in body)
        if result.status in BLOCK_CODES or keyword_hits >= 2:
            return "bloqueado"
        compact_payload = re.sub(r"[^a-z0-9]", "", payload.lower())[:14]
        compact_body = re.sub(r"[^a-z0-9]", "", body[:5000])
        if compact_payload and compact_payload in compact_body:
            return "reflejado"
        return "permitido"

    def _header_waf_signal(self, result: Any) -> str:
        if not result:
            return ""
        headers = {str(key).lower(): str(value) for key, value in result.headers.items()}
        server = headers.get("server", "").lower()
        cookies = " ".join(
            value.lower()
            for key, value in headers.items()
            if key == "set-cookie" or key.startswith("set-cookie")
        )
        body = str(getattr(result, "text", "") or "").lower()[:20000]
        matched: list[str] = []
        for name, markers in WAF_HEADER_SIGNATURES.items():
            if any(marker in headers for marker in markers):
                matched.append(name)
        for name, markers in WAF_COOKIE_SIGNATURES.items():
            if any(marker in cookies for marker in markers):
                matched.append(name)
        for name, markers in WAF_BODY_SIGNATURES.items():
            if any(marker in body for marker in markers):
                matched.append(name)
        if "cloudflare" in server and "Cloudflare" not in matched:
            matched.append("Cloudflare")
        if "akamai" in server and "Akamai" not in matched:
            matched.append("Akamai")
        return " | ".join(dict.fromkeys(matched))

    @staticmethod
    def _mixed_case(payload: str) -> str:
        out = []
        upper = True
        for char in payload:
            out.append(char.upper() if upper else char.lower())
            if char.isalpha():
                upper = not upper
        return "".join(out)

    @staticmethod
    def _unicode_compat(payload: str) -> str:
        mapping = {
            "<": "＜",
            ">": "＞",
            "'": "＇",
            '"': "＂",
            " ": "\u2000",
            "/": "∕",
            "=": "＝",
            "(": "（",
            ")": "）",
        }
        return "".join(mapping.get(char, char) for char in payload)
